version: '3.9'

services:
  followers-managment:
    build:
      dockerfile: dockerfile
      context: ./followers
    image: microservice-followers:final
    container_name: followers-cont
    restars: always
    networks:
      - followers_server
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      # NoSQL: environment variable holding connection URI for Neo4J database
      # Local DB instance
      - NEO4J_DB=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=followers
    depends_on:
      neo4j:
        condition: service_healthy  

  # NoSQL: Neo4J DB
  neo4j:
    image: neo4j
    restart: always
    ports:
      # bolt
      - "7687:7687"
      # http
      - "7474:7474"
      # https
      - "7473:7473"
    # Docker healtcheck - checks if database is "alive"
    healthcheck:
      # test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a <NEO4J_dbms_connector_bolt_listen__address> -u <user defined username> -p <user defined password> || exit 1" ]
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p followers || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - NEO4J_AUTH=neo4j/followers
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:   